---
title: "wk1_day4_matrix"
format: html
---

## create matrices in R

```{r}
# create sequence of values ----
my_values <-seq(from = 1, to = 10, by = 1)
my_values

# convert to matrix ----
my_matrix <- matrix(data = my_values, 
                    nrow = 2, 
                    ncol = 5, 
                    byrow = TRUE)
my_matrix

class(my_matrix)
```

```{r}
# if nrow and ncol misaligned, will give warning and omit data
matrix(data = my_values, nrow = 2, ncol = 3, byrow = TRUE)
matrix(data = my_values, nrow = 2, ncol = 4, byrow = TRUE)
```

```{r}
# scalar multiplication ----
4* my_matrix

# create a second matrix
my_values2 <- seq(from = 21, to = 30, by = 1)
my_matrix2 <- matrix(data = my_values2, nrow = 2, ncol = 5, byrow = TRUE)

my_matrix2
my_matrix

dim(my_matrix)
dim(my_matrix2)
# add matricies ----
my_matrix + my_matrix2

# sub matricies ----
my_matrix2 - my_matrix

# dot product ----
as.vector(my_matrix) * my_matrix2

```



```{r}
# make a couple 2x2 matricies

cats <- matrix(data = c(0, 4, 3 ,1), nrow = 2, byrow = TRUE)
dogs <- matrix(data = c(6, -3, 0, 2), nrow = 2, byrow = TRUE)
dim(cats)
dim(dogs)

# dot product ----
cats %*% dogs
```
# leslie matrix ex

```{r}

insect_leslie <- matrix(data = c(0,0,600,0.2,0,0,0,0.08,0),
                        nrow = 3,
                        ncol = 3,
                        byrow = TRUE)
insect_leslie

# initial starting conditions ----
# eggs, larvae, females
insect_y0 <- c(12000, 700, 500)

#pop @ yr 1 ----
insect_y1 <- insect_leslie %*% insect_y0
insect_y1
```

